/**
 * WorldManager.js
 * ─────────────────────────────────────────────────────────────
 * Owns the logical world graph generated by Stage 2's WorldGenerator.
 * Provides logical node queries and specifications to physics,
 * roads, sensors, and missions.
 */

import { WorldGenerator } from '../../../engine/procgen/WorldGenerator.js';

/**
 * Initialises the world using Stage 2's verified procedural world generator.
 * @param {Object} state – GameState
 * @returns {Promise<Object>} WorldContext
 */
export async function initWorld(state = {}) {
  const seed = state.seed ?? 42;
  const difficulty = state.difficulty ?? 'medium';

  const generator = new WorldGenerator({
    network: {
      gridWidth: 5,
      gridHeight: 5,
      nodeSpacing: 14,
      elevationScale: 15,
      extraEdgeRatio: 0.35,
    },
    placement: {
      difficulty,
    },
    validation: {
      requireDeductiveProof: true,
    },
  });

  const generated = generator.generateWorld(seed);

  if (!generated.valid) {
    console.error('[world] World generation failed validation after max retries!');
  } else {
    console.log(`[world] Procedural world validated and accepted (seed: ${generated.effectiveSeed}, attempts: ${generated.attempts})`);
  }

  const graph = generated.graph;
  const spec = generated.spec;

  return {
    graph,
    spec,
    spawnNode: spec.startId,
    getNode: (id) => graph.nodes.get(id),
    getNeighbors: (id) => graph.getNeighbors(id),
  };
}
